version: "3.9"
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./App/frontend/build:/usr/share/nginx/html/
      - ./local/data/local_data/img:/usr/share/nginx/html/images/
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - web
      - db

  web:
    restart: always
    build: .
    expose:
      - "80"
    depends_on:
      - db
    environment:
      DB_NAME: db
      DB_USER: root
    volumes:
      - ./App:/dodomoa/App
    working_dir: /dodomoa/App
    command:
      [
        "gunicorn",
        "main:app",
        "--workers",
        '2',
        '--worker-class',
        'uvicorn.workers.UvicornWorker',
        "--bind",
        '0.0.0.0:80'
      ]

  db:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: dodomoa_db
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    expose:
      - "3306"
